// <auto-generated />
using System;
using ArachnidBot;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ArachnidBot.Migrations
{
    [DbContext(typeof(ArachnidContext))]
    [Migration("20230303092540_AdditionalPropertiesForUserAssociations")]
    partial class AdditionalPropertiesForUserAssociations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArachnidBot.UserAssociation", b =>
                {
                    b.Property<long>("UserTelegramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("UserTelegramId"));

                    b.Property<string>("DiscordName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TelegramName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("UserDiscordId")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("UserTelegramId");

                    b.HasAlternateKey("UserDiscordId");

                    b.ToTable("UserAssociations");
                });
#pragma warning restore 612, 618
        }
    }
}
